pom.xml
* Updated private API contains the recently added forename and surname fields.
=> GCI-773 Make Orders API depend on updated private SDK

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/model/Item.java, src/main/java/uk/gov/companieshouse/orders/api/model/ItemCosts.java, src/main/java/uk/gov/companieshouse/orders/api/model/ProductType.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToCertificateMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapperTest.java
* Changes made to the Certificates API costs fields to support multiple product codes now reflected here in resources made available by the Orders API too.
* This excludes anything that may be required to reflect the same changes in basket resources. Basket resources will be dealt with later in task GCI-797.
=> GCI-780/GCI-781: Align checkout and order resources with updated spec

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java
Changes response status of create `checkout` endpoint based on the `totalOrderCost` of the `checkout` object.
=> Update response status handling

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/client/Api.java, src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapper.java, src/main/java/uk/gov/companieshouse/orders/api/service/ApiClientService.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/ApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java, src/test/java/uk/gov/companieshouse/orders/api/util/TimestampedEntityVerifier.java
Implements callback to the payments api when the patch endpoint on the payment-details URL has been hit. 
This verifies the payment exists, is paid, is the same amount as the checkout, and has the correct url as a resource before marking the checkout as paid. 
If the incoming patch request does not have a "paid" status the checkout is instead changed the incoming status, and the basket is not cleared.
Resolves: GCI-427 
Related PR's for story: 
https://github.com/companieshouse/api-sdk-manager-java-library/pull/7
https://github.com/companieshouse/payments.api.ch.gov.uk/pull/124
=> GCI-427: Check payment with payments.api when patching order

src/main/java/uk/gov/companieshouse/orders/api/dto/BasketItemDTO.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/ItemMapperTest.java
Adds the missing `id` property to `BasketItemDTO` so the `basketItem` resource contains the `id` property when 'Add item to basket' is requested.
=> Add id attribute and update test

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/exception/ErrorType.java, src/main/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidator.java, src/main/java/uk/gov/companieshouse/orders/api/validator/DeliveryDetailsValidator.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java, src/test/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidatorTest.java
Ensures delivery details are present when checkout requested for basket item that needs postal delivery.
=> Add validation to catch missing delivery details for postal delivery request

src/test/resources/application.properties
This is a fix for the Surefire plugin failure test. The failure was due to embedded Kafka's inability to access default log directory in /var folder. This property addition to tests allows Kafka to use a folder that is inside `target` folder giving it full access to read and write.
=> Change Kafka log dir to where it has rw access for tests

src/test/java/uk/gov/companieshouse/orders/api/OrdersApiApplicationTests.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/HealthcheckControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthorisationTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java, src/test/java/uk/gov/companieshouse/orders/api/util/FieldNameConverterTest.java, src/test/resources/application.properties
This follows up the previous attempt to fix Surefire build issue by resetting Spring context before running each embedded Kafka integration test. The build failures were a result of Kafka log `.lock` file being contested for by each integration test thread. This change clears the context using the `@DirtiesContext` annotation.
=> Reset spring context before running embedded kafka integration tests

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/dto/BasketItemDTO.java, src/main/java/uk/gov/companieshouse/orders/api/listener/MongoCheckoutListener.java, src/main/java/uk/gov/companieshouse/orders/api/mapper/ApiToCertificateMapper.java, src/main/java/uk/gov/companieshouse/orders/api/mapper/ApiToItemMapper.java, src/main/java/uk/gov/companieshouse/orders/api/model/Certificate.java, src/main/java/uk/gov/companieshouse/orders/api/model/CertificateItemOptions.java, src/main/java/uk/gov/companieshouse/orders/api/model/CertifiedCopy.java, src/main/java/uk/gov/companieshouse/orders/api/model/CertifiedCopyItemOptions.java, src/main/java/uk/gov/companieshouse/orders/api/model/FilingHistoryDocument.java, src/main/java/uk/gov/companieshouse/orders/api/model/Item.java, src/main/java/uk/gov/companieshouse/orders/api/model/ItemOptions.java, src/main/java/uk/gov/companieshouse/orders/api/service/ApiClientService.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java, src/test/java/uk/gov/companieshouse/orders/api/listener/MongoCheckoutListenerTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToCertificateMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToItemMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/ApiClientServiceIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/ApiClientServiceTest.java, src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java, src/test/java/uk/gov/companieshouse/orders/api/util/TestUtils.java, src/test/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidatorTest.java, src/test/postman/Orders_API.postman_collection.json, src/test/resources/application.properties
* Functionality broadened so that either a certificate or a certified copy item may be added to the basket, and the details of the item viewed in the response to a get basket request.
* Further changes subsequently made to get the item options held in checkouts to deserialise correctly from the DB. The core of these changes is the introduction of the `MongoCheckoutListener`.
=> GCI-1022: Add certified copy item to basket

src/main/java/uk/gov/companieshouse/orders/api/listener/MongoCheckoutListener.java, src/main/java/uk/gov/companieshouse/orders/api/listener/MongoOrderListener.java, src/main/java/uk/gov/companieshouse/orders/api/listener/OrderItemOptionsReader.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/listener/MongoCheckoutListenerTest.java, src/test/java/uk/gov/companieshouse/orders/api/listener/MongoOrderListenerTest.java, src/test/java/uk/gov/companieshouse/orders/api/listener/OrderItemOptionsReaderTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapperTest.java
* Refactor Mongo checkout reader to introduce similar Mongo order reader so that item options held within checkouts or orders can be read correctly from the database.
* Verify that the options are rendered correctly in responses and/or stored correctly in DB collections for `add item`, `get basket`, `checkout basket`, `patch successful payment` and `get order` scenarios/requests. 
* These changes should fix [GCI-1286](https://companieshouse.atlassian.net/browse/GCI-1286).
=> GCI-984: Allow checkout of certified copies in Orders API

src/main/java/uk/gov/companieshouse/orders/api/controller/GlobalExceptionHandler.java, src/main/java/uk/gov/companieshouse/orders/api/exception/KafkaMessagingException.java, src/main/java/uk/gov/companieshouse/orders/api/kafka/OrderReceivedMessageProducer.java, src/main/java/uk/gov/companieshouse/orders/api/kafka/OrdersKafkaProducer.java, src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/orders/api/controller/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/companieshouse/orders/api/kafka/OrdersKafkaProducerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/kafka/OrdersMessageProducerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/OrderServiceTest.java
This change replaces the `send()` method call with async call to `sendAndReturnFuture()` that returns the `offset` of the message sent to Kafka topic. The received `offset` is logged together with `order_id` for ease traceability.
=> Gci 1297 verify message is written to kafka topic

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/model/MissingImageDeliveryItemOptions.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Add `filing_history_category` attribute to `item_options`
=> Add support for filing history category attribute

pom.xml
Jacoco reports are not being generated correctly resulting in code coverage being reported as 0% in Sonar. This will fix the issue by removing the Jacoco config and pointing to a newer version of the parent pom which contains the correct config.
=> Update jacoco config

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java, src/main/java/uk/gov/companieshouse/orders/api/exception/ResourceNotFoundException.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepository.java, src/main/java/uk/gov/companieshouse/orders/api/repository/CheckoutRepository.java, src/main/java/uk/gov/companieshouse/orders/api/repository/OrderRepository.java
Using `@RepositoryRestResource` is generating a separate set of endpoints that we do not want to expose.
We'll remove the Spring Data REST dependency and keep just our defined endpoints.
=> Remove Spring Data REST

pom.xml
Upgrade to the latest version which limits transitive dependencies.
Explicitly add `spring-boot-starter-web` which used to be a transitive dependency of `api-security-java`
=> Bump api-security-java library

src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java, src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java
This unit test is currently testing functionality with the `ENABLE_TOKEN_PERMISSION_AUTH` feature flag off (default is off) but the flag is now ON in live and we should be testing that behaviour instead.
Note the feature flag is being removed in FA-1070 and this change will help ensuring nothing breaks
=> Amend unit test to work with the new feature flag on

pom.xml, src/main/java/uk/gov/companieshouse/orders/api/interceptor/LoggingInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/model/CertificateItemOptions.java, src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
* Add company_status field to certificate item options.
* Fix compilation warnings caused by use of deprecated classes.
* Fix an issue causing NPEs to be thrown by the MapStruct annotation
processer when run in IntelliJ.
* Tested locally, working.
Resolves:
[BI-10173](https://companieshouse.atlassian.net/browse/BI-10173)
=> BI-10173 Add company status field to item options

src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
* Use SecurityManager for authenticating/authorising requests to get
checkout endpoint.
=> GCI-2003 Rework auth for get checkout endpoint

src/main/java/uk/gov/companieshouse/orders/api/model/BasketData.java
* Field data.enrolled used to determine whether user is enrolled for
multi-item baskets or not.
Resolves:
[GCI-2168](https://companieshouse.atlassian.net/browse/GCI-2168)
=> GCI-2168 Add enrolled field to BasketData

src/main/java/uk/gov/companieshouse/orders/api/model/BasketData.java, src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryImpl.java, src/test/java/uk/gov/companieshouse/orders/api/repository/BasketRespositoryImplTest.java
* Preserve value of new data.enrolled field across multiple orders.
Resolves:
[GCI-2172](https://companieshouse.atlassian.net/browse/GCI-2172)
=> GCI-2172 Preserve value of data.enrolled

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/service/ItemEnricher.java, src/main/java/uk/gov/companieshouse/orders/api/service/ItemEnrichmentException.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/ItemEnricherTest.java
* Add support for baskets containing multiple items to getBasket
endpoint in BasketController.
* Related item resources will be fetched by URI in parallel and mapped
to the corresponding item model.
=> GCI-2171 Add multi-item support to getBasket endpoint

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
* If a user tries to remove an item that does not exist in the basket the api will return HTTP 409 CONFLICT
[GCI-2158](https://companieshouse.atlassian.net/browse/GCI-2158)
=> GCI-2158 Return HTTP 409 CONFLICT when item not in basket

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapper.java, src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java, src/main/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidator.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java, src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapperTest.java, src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java, src/test/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidatorTest.java
* Change BaskerController to support multiple item processing, used to calculate correct total costs
* Change CheckoutBasketValidator to allow multi items to be processed
* Change CheckoutToPaymentDetailsMapper for multi item support, used for getting payment details
* Remove the setCompanyNumber mapping in the above mapper
* **Tested journey locally with API changes, confirm that everything works as expected.**
Resolves [GCI-2209 Total should be calculated from all items in basket](https://companieshouse.atlassian.net/browse/GCI-2209)
=> GCI-2209 Multi-item support for CheckoutBasket endpoint

src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestUris.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java, src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java, src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java, src/test/java/uk/gov/companieshouse/orders/api/service/OrderServiceTest.java, src/test/java/uk/gov/companieshouse/orders/api/util/StubHelper.java
* Implement new getOrderItem controller endpoint and related service
method.
* Endpoint searches existing order for matching item by ID. If no
matching item found then HTTP 404 Not Found returned.
Resolves:
[GCI-2265](https://companieshouse.atlassian.net/browse/GCI-2265)
=> GCI-2265 implement new getOrderItem endpoint

terraform/groups/ecs-service/locals.tf
PR to test new listener path for Load balancer 'cidev-priv-api-lb-orders-api'
=> fix: update listener path

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
https://companieshouse.slack.com/archives/CMFDF43KM/p1717592689650029
Some endpoints for orders end in just /basket , so we need to modify the listener rules to account for this
=> fix: update listener rule and remove log_level

src/main/java/uk/gov/companieshouse/orders/api/OrdersApiApplication.java
This updates the system timezone to London to resolve datetime issues during BST (UTC+1) being reported incorrectly.
=> BI-13910: Update system default time zone

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/main/java/uk/gov/companieshouse/orders/api/dto/BasketPaymentRequestDTO.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
This ensures that the `paid_at` value in the patch request that updates the `checkout` resource with the payment status saves the datetime correctly to Mongo using the correct UTC date time. Due to the timezone of the application now being set to `Europe/London` a LocalDateTime was having it saved an hour before due to no timezone data in a LocalDateTime object.
=> BI-13910: Fix paid_at datetime conversion

src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java, src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
Resolves [BI-13973](https://companieshouse.atlassian.net/browse/BI-13973) 
Add dummy reference for free admin orders so that payment reference field can sucessfully reach ORDER-DETAILS and ORDER-HEADER table when passing through chd-order-api and chd-order-consumer.
[BI-13973]: https://companieshouse.atlassian.net/browse/BI-13973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set static payment reference for free admin orders
