companieshouse/orders.api.ch.gov.uk

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/model/BasketData.java
- src/main/java/uk/gov/companieshouse/orders/api/model/Checkout.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutData.java
- src/main/java/uk/gov/companieshouse/orders/api/model/DirectorOrSecretaryDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/RegisteredOfficeAddressDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
Return 400 bad request when posting to /basket/checkout and added userId.
resolves: PCI-707
> return 400 bad request when posting to /basket/checkout and added userId

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/dto/BasketPaymentRequestDTO.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/postman/Orders_API.postman_collection.json
- src/test/resources/application.properties
added PATCH /basket/checkout endpoint
resolves: PCI-605
> added PATCH /basket/checkout endpoint

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/dto/BasketPaymentRequestDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/model/PaymentStatus.java
- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepository.java
- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryCustom.java
- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryImpl.java
- src/main/java/uk/gov/companieshouse/orders/api/service/BasketService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/repository/BasketRespositoryImplTest.java
Clear basket once payment has been patched
resolves: PCI-608
> Clear basket once payment has been patched

- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryImpl.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Update updated_at field
resolves: PCI-743
> Update updated_at field

- src/main/java/uk/gov/companieshouse/orders/api/dto/AddDeliveryDetailsRequestDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/mapper/DeliveryDetailsMapper.java
- src/main/java/uk/gov/companieshouse/orders/api/validator/DeliveryDetailsValidator.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/DeliveryDetailsMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/validator/DeliveryDetailsValidatorTest.java
- src/test/postman/Orders_API.postman_collection.json
Modified request object for add delivery details
resolves: PCI-715
> Modified request object for add delivery details

- src/main/java/uk/gov/companieshouse/orders/api/model/DeliveryDetails.java
Added annotation to store address line 1 as address_line_1 instead of address_line1, same has been done for address line 2
> Added annotation to store address correctly

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/postman/Orders_API.postman_collection.json
- src/test/resources/application.properties
* Align checkout basket URL with API spec.
* Align update checkout payment details URL with API spec.
> PCI-782: Sync up request URLs with API spec

- routes.yaml
- src/main/java/uk/gov/companieshouse/orders/api/OrdersApiApplication.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapper.java
- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
get an order
resolves: GCI-708
> Gci 708 get an order

- src/test/postman/Orders_API.postman_collection.json
added postman collection for get an order
resolves: GCI-708
> added postman collection for get an order

- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
Added EmbeddedKafka annotation to OrderControllerIntegrationTest
resolves: GCI-708
> added EmbeddedKafka annotation to OrderControllerIntegrationTest

- README.md
README updated with endpoint details
> Update paymentDetials endpoint details

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/model/AbstractOrderData.java
- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
Added delivery details to checkout
resolves: GCI-784
> Added delivery details to checkout

- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Fixed delivery details unit test
resolves: GCI-784
> Fixed delivery details unit test

- src/main/java/uk/gov/companieshouse/orders/api/dto/BasketPaymentRequestDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/dto/ItemDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapper.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToPaymentDetailsMapperTest.java
Added description to get payments.
resolves: GCI-962
> added description to get payments

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/config/ApplicationConfig.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapper.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthorisationTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java
* Implemented authorisation for the Orders API, according to the requirements captured in the Authorisation column of the two tables on this page: https://companieshouse.atlassian.net/wiki/spaces/CHS/pages/1515684399/GCI-926+Investigate+authentication+and+authorisation+checks+in+Orders+API.
> GCI-951: Implement authorisation

- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/main/java/uk/gov/companieshouse/orders/api/util/CheckoutHelper.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
- src/test/java/uk/gov/companieshouse/orders/api/util/CheckoutHelperTest.java
Implements logic to calculate `total_order_cost` of `checkout` object.
> GCI-776 show order total cost when checking out

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/exception/ErrorType.java
- src/main/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidator.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidatorTest.java
Implements validation logic that confirms the validity of item in basket, returning 400 otherwise.
> Gci 826 patch basket to validate item uri with certificates api

- src/main/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidator.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Fixes missing dependency injection annotation.
> Gci 826 patch basket to validate item uri with certificates api fix

- src/main/java/uk/gov/companieshouse/orders/api/dto/DeliveryDetailsDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/model/DeliveryDetails.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/CheckoutToOrderMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/DeliveryDetailsMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
- src/test/java/uk/gov/companieshouse/orders/api/validator/DeliveryDetailsValidatorTest.java
> Remove unused premises field

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapper.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/postman/Orders_API.postman_collection.json
- Update URL to be generic rather than being dedicated to PATCH
- Add get basket method
Resolves: GCI-1062
> Add Get Basket Method

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
> Check for if items exists - required for first pass of journey

- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
refactored order id to ORD-######-######
resolves: GCI-1099
> Gci 1099 refactor orderid

- src/main/java/uk/gov/companieshouse/orders/api/config/MongoConfig.java
- src/main/java/uk/gov/companieshouse/orders/api/converter/LocalDateTimeConverter.java
- src/main/java/uk/gov/companieshouse/orders/api/converter/LocalDateTimeToStringConverterFactory.java
- src/main/java/uk/gov/companieshouse/orders/api/converter/StringToLocalDateTimeConverterFactory.java
- src/test/java/uk/gov/companieshouse/orders/api/converter/LocalDateTimeConverterTest.java
Added ConversionFactory classes to convert between String and LocalDateTime objects.
GCI-1011
> Bug fix for date error in patch

- src/test/java/uk/gov/companieshouse/orders/api/converter/LocalDateTimeConverterTest.java
Refactored unit test as was causing a failure in concourse build
> Refactored unit test as was causing a failure in concourse build

- src/main/java/uk/gov/companieshouse/orders/api/model/PaymentStatus.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Added check for cancelled payments
resolves: GCI-1111
> Added check for cancelled payments

- src/main/java/uk/gov/companieshouse/orders/api/OrdersApiApplication.java
Removed time zone specification to ensure consistency with other logs
> Removed time zone specification to ensure consistency with other logs

- src/main/java/uk/gov/companieshouse/orders/api/OrdersApiApplication.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/LoggingInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/kafka/OrderReceivedMessageProducer.java
- src/main/java/uk/gov/companieshouse/orders/api/kafka/OrdersKafkaProducer.java
- src/main/java/uk/gov/companieshouse/orders/api/kafka/OrdersMessageFactory.java
- src/main/java/uk/gov/companieshouse/orders/api/logging/LoggingUtils.java
- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
- src/main/java/uk/gov/companieshouse/orders/api/validator/CheckoutBasketValidator.java
- src/test/java/uk/gov/companieshouse/orders/api/kafka/OrdersMessageConsumer.java
Enhanced logging with structure which conforms to Companies House logging guidelines
GCI-1078
> Enhanced Logging for Orders API

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
Amendments to stop unit tests failing
> Amendments made to fix failing unit tests

- src/main/java/uk/gov/companieshouse/orders/api/kafka/OrdersKafkaProducer.java
- src/main/java/uk/gov/companieshouse/orders/api/mapper/ItemMapper.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/kafka/OrdersMessageConsumer.java
- src/test/resources/application.properties
Updates kafka broker address property names to use Spring Kafka property names.
> Gci 1129 surefire error in tests when building orders api

- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryImpl.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/repository/BasketRespositoryImplTest.java
This update adds delivery details (back) into the basket while resetting it on successful payment.
> Add delivery details to basket when clearing it

- pom.xml
Amendments made to upgrade spring boot to 2.1.15.RELEASE.
Jira ticket - GCI-1265
> Upgraded spring dependency version to 2.1.15.RELEASE part of GCI-1265

- src/test/postman/Payments_API.postman_collection.json
* Includes request to create payment session as described here: https://companieshouse.atlassian.net/wiki/spaces/CHS/pages/1603764496/GCI-993+Investigation+into+the+work+required+for+payment+reconciliation#Create-a-payment-session.
> GCI-1032: Add Payments API requests useful for emulating payment

- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
This swaps order of method call to Kafka message sending with Order creation.
> Move call to Kafka message sending after Order creation.

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/model/FilingHistoryDocument.java
- src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java
Recent addition to certified copies api required adding field to orders api
> Implement filing_history_cost within orders api

- src/main/java/uk/gov/companieshouse/orders/api/OrdersApiApplication.java
- src/main/java/uk/gov/companieshouse/orders/api/environment/RequiredEnvironmentVariables.java
- src/main/java/uk/gov/companieshouse/orders/api/logging/LoggingUtils.java
- src/test/java/uk/gov/companieshouse/orders/api/OrdersApiApplicationTests.java
This adds a check for missing environment variables that prevents the pp from starting check fails.
> GCI-1317 add env variable check to prevent app starting

- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java
added integration tests for patch payment for MID
resolves: GCI-889
> added integration tests for patch payment for MID

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/model/CertificateType.java
bump sdk version 
updated dissolved cert enum
Resolves: GCI-1422
> updated dissolved certs enum

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/model/MissingImageDeliveryItemOptions.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToItemMapperTest.java
> Add barcode to missing image delivery item options

- pom.xml
This resolves the error as an older version of java sdk was being used
> bump java sdk version

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/model/CertificateItemOptions.java
- src/main/java/uk/gov/companieshouse/orders/api/model/DesignatedMemberDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/GeneralPartnerDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/LimitedPartnerDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/MemberDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/PrincipalPlaceOfBusinessDetails.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToItemMapperTest.java
* Add new fields representing the company type and general nature of business
* Add new classes representing designated members and members
* Add new classes representing general partners and limited partners
* Add new class representing the principal place of business
> BI-8761 Add new fields for the LLP/LP certificate order journey

- routes.yaml
- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/service/OrderServiceTest.java
- src/test/resources/application.properties
> BI-6862 - Add get checkout method

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/config/MongoConfig.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapper.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/GlobalExceptionHandlerTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/listener/OrderItemOptionsReaderTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Updated deps to 2.5.5 
Resolves: GCI-1943
> Gci 1943 springboot upgrade for mongodb

- pom.xml
- src/test/java/uk/gov/companieshouse/orders/api/kafka/OrdersKafkaProducerIntegrationTest.java
* Attempt field has been added to order-received model.
Resolves:
[BI-9971](https://companieshouse.atlassian.net/browse/BI-9971)
> BI-9971 Upgrade kafka-models version

- pom.xml
DEBT-1461
Updated to prevent log4j exploit
> Updated to prevent log4j exploit

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/model/AdministratorsDetails.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CertificateItemOptions.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/ApiToItemMapperTest.java
- Add administrators details to models
- Tested locally using postman, works fine
[BI-9854](https://companieshouse.atlassian.net/browse/BI-9854)
> BI-9854 Add administrators details to models

- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrdersSearchDisabledIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- Validates requests by checking for existence of an api key and internal user role
[GCI-2078](https://companieshouse.atlassian.net/browse/GCI-2078)
> GCI-2078 - Validate authorisation of orders search requests

- src/main/java/uk/gov/companieshouse/orders/api/repository/OrderRepository.java
- src/test/java/uk/gov/companieshouse/orders/api/repository/OrderRepositoryIntegrationTest.java
- Ignore case when searching orders by email
[GCI-2126](https://companieshouse.atlassian.net/browse/GCI-2126)
> GCI-2126 Ignore case when searching orders by email

- README.md
- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestUris.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/postman/Orders_API.postman_collection.json
* New endpoint re-submits the message for the successfully paid for order to the `order-received` Kafka topic.
> BI-11304: Reprocess order endpoint

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/dto/BasketRequestDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestUris.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/mapper/BasketMapper.java
- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryCustom.java
- src/main/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryImpl.java
- src/main/java/uk/gov/companieshouse/orders/api/service/BasketService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthenticationTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/OrdersApiAuthorisationTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/BasketMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/BasketServiceTest.java
- src/test/java/uk/gov/companieshouse/orders/api/util/StubHelper.java
* Adds an endpoint to the basket controller to remove items within a basket.
[GCI-2179](https://companieshouse.atlassian.net/browse/GCI-2179)
> GCI-2179 Implement remove basket item endpoint

- src/main/java/uk/gov/companieshouse/orders/api/model/Basket.java
- src/main/java/uk/gov/companieshouse/orders/api/service/BasketService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/repository/BasketRepositoryIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/BasketServiceTest.java
Removes duplicate getter and setter for list of items within a basket
Resolves [GCI-2191](https://companieshouse.atlassian.net/browse/GCI-2191)
> GCI-2191 Remove getter and setter for items in basket

- src/main/java/uk/gov/companieshouse/orders/api/config/ApplicationConfig.java
- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/BasketEnrollmentFeatureToggle.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestUris.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/model/ApiError.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/config/ApplicationConfigTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/BasketEnrollmentFeatureToggleTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapperTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/resources/application.properties
* New endpoint appends item reference to items array in basket.
* If item URI already exists in basket, skip item.
* If user is disenrolled, return HTTP 404 Not Found.
Resolves:
[GCI-2204](https://companieshouse.atlassian.net/browse/GCI-2204)
> GCI-2204 Append item to basket endpoint

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/exception/ErrorType.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
- src/test/resources/application.properties
* BasketController.appendItemToBasket now returns HTTP 400 Bad Request
if BASKET_ITEM_LIMIT exceeded.
> GCI-2291 Implement configurable limit on basket size

- pom.xml
- src/main/java/uk/gov/companieshouse/orders/api/dto/DeliveryDetailsDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/model/DeliveryDetails.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/mapper/DeliveryDetailsMapperTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
Delivery details now contains an optional company name field
Resolves: GCI-2299
> add company name field to delivery details

- src/main/java/uk/gov/companieshouse/orders/api/config/FeatureOptions.java
- src/main/java/uk/gov/companieshouse/orders/api/config/FeatureOptionsConfig.java
- src/main/java/uk/gov/companieshouse/orders/api/exception/ServiceException.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutSummary.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutSummaryBuildable.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutSummaryBuilderFactory.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutSummaryInvocationHandler.java
- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrdersSearchMultibasketDisabledIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/model/CheckoutSummaryInvocationHandlerTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
- src/test/java/uk/gov/companieshouse/orders/api/util/TestConstants.java
- src/test/resources/application.properties
* Skip mapping of companyNumber, productLine fields if
ORDERS_SEARCH_MULTIBASKET_ENABLED=true.
> GCI-2203 Toggle checkout search fields

- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/model/Checkout.java
- src/main/java/uk/gov/companieshouse/orders/api/model/CheckoutData.java
- src/main/java/uk/gov/companieshouse/orders/api/service/CheckoutService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/service/CheckoutServiceTest.java
* Changes get checkout item endpoint to return a checkout with the specified item embedded inside it
* Rather than the item by itself
[GCI-2335](https://companieshouse.atlassian.net/browse/GCI-2335)
> GCI-2239 Change get checkout item endpoint to return checkout with embedded item

- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
* Changes getCheckoutItem endpoint to return a CheckoutData object not a Checkout object
[GCI-2335](https://companieshouse.atlassian.net/browse/GCI-2335)
> GCI-2335 Change getCheckoutItem to return checkout data

- src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
- src/main/java/uk/gov/companieshouse/orders/api/dto/PatchOrderedItemDTO.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestUris.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptor.java
- src/main/java/uk/gov/companieshouse/orders/api/model/Item.java
- src/main/java/uk/gov/companieshouse/orders/api/model/ItemStatus.java
- src/main/java/uk/gov/companieshouse/orders/api/service/OrderService.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/OrderControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthenticationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/interceptor/UserAuthorisationInterceptorTests.java
- src/test/java/uk/gov/companieshouse/orders/api/service/OrderServiceTest.java
- Implement order item patch controller and service methods
- Add patch order item to authentication and authorisation interceptors
-  Update tests 
Resolves: DCAC-256, DCAC-257
> DCAC-256, DCAC-257 - PATCH order item method

- src/test/postman/Orders_API.postman_collection.json
* Will facilitate development for this story.
> DCAC-216: Add a patch ordered item Postman test request

- src/test/postman/Orders_API.postman_collection.json
* It seems the first time I did this, I did not notice I had not saved the updated state of the new request at the right point? 👎 
* Doing it again to capture the request as it should be.
* As I noticed on reloading the collection that it did not have the required config to allow the refreshing of the session token using the variables in our environments, I have added this too.
> DCAC-216: Add a patch ordered item Postman test request (again)

- pom.xml
All tests passed.
Ensuring all vulnerabilities are gone.
> Ju 89 java 21 migration - removing 2 medium vulnerabilities.

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/main/java/uk/gov/companieshouse/orders/api/model/PaymentStatus.java
Fulfils [BI-12452](https://companieshouse.atlassian.net/browse/BI-12452)
Add 'free' to payment status and update checkout status when free order is being processed
[BI-12452]: https://companieshouse.atlassian.net/browse/BI-12452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-12452 - Update checkout status for free order

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
Resolves [BI-12452](https://companieshouse.atlassian.net/browse/BI-12452)
Moves the checkout status update from the Checkout basket method to the Patch basket payment details method
[BI-12452]: https://companieshouse.atlassian.net/browse/BI-12452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-12452 - Update checkout status for free orders

- src/main/java/uk/gov/companieshouse/orders/api/controller/BasketController.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/orders/api/controller/BasketControllerTest.java
Proposed fix for BI-12452.
This saves the checkout object for free orders (payment ref/status)
> Bi 12452 proposed fix free checkout status

- pom.xml
Add sonarqubereport analysis
Fulfills part of [ASM-469](https://companieshouse.atlassian.net/browse/ASM-469)
[ASM-469]: https://companieshouse.atlassian.net/browse/ASM-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add sonarQube analysis report

- README.md
Delete extra line space to trigger build
> Delete extra line space to trigger build
